name: CICD
on: 
  push:
    branches: main
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps: 
      - name: docker login
        uses: docker/login-action@v3.1.0
        with:
          username: kishorekiku007
          password: Kishore@123
      - name: Docker artifact build
        uses: actions/checkout@v4
        run: docker build -t acephish . && docker tag kishorekiku007/acephish && docker push kishorekiku007/acephish:latest
  continuousDeployment:
    runs-on: ubuntu-latest
    needs: continuousIntegration
    steps:
      - name: docker login
        uses: docker/login-action@v3.1.0
        with:
          username: kishorekiku007
          password: Kishore@123
      - name: Deployment
        run: docker pull kishorekiku007/acephish:latest && docker run -p 5000:5000 kishorekiku007/acephish 
